export const productsData = [
  {
    id: 1,
    title: "Samsung S21",
    description: "black in color",
    price: "2500",
    img: "/images/1.jpg",
    quantity: 1,
  },
  {
    id: 2,
    title: "Samsung M32",
    description: "white in color",
    price: "2300",
    img: "/images/2.jpg",
    quantity: 1,
  },
  {
    id: 3,
    title: "Redmi 9",
    description: "black in color",
    price: "3500",
    img: "/images/3.jpg",
    quantity: 1,
  },
  {
    id: 4,
    title: "Iphone 14 Max Pro",
    description: "Best mobile ever",
    price: "90500",
    img: "/images/4.jpg",
    quantity: 1,
  },
  {
    id: 5,
    title: "Realme 9 pro",
    description: "black in color",
    price: "2500",
    img: "/images/5.jpg",
    quantity: 1,
  },
  {
    id: 6,
    title: "Realme c17",
    description: "black in color",
    price: "3500",
    img: "/images/6.jpg",
    quantity: 1,
  },
  {
    id: 7,
    title: "Samsung A71 5G",
    description: "black in color",
    price: "2500",
    img: "/images/7.jpg",
    quantity: 1,
  },
  {
    id: 8,
    title: "Iphone 12",
    description: "Best mobile ever",
    price: "90500",
    img: "/images/8.jpg",
    quantity: 1,
  },
  {
    id: 9,
    title: "Xaoimo Redmi Note 11 Pro",
    description: "black in color",
    price: "2500",
    img: "/images/9.jpg",
    quantity: 1,
  },
];